<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.8.2 on win32)" generated="2024-02-06T18:31:11.421265" rpa="false" schemaversion="5">
<suite id="s1" name="SalesTracker login csv" source="C:\Users\imranuddinms\PycharmProjects\SaleTracker_Automation\Tests\NormalWay\SalesTracker_login_csv.robot">
<test id="s1-t1" name="Verifying credentials" line="11">
<kw name="Start Testcases" type="SETUP">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-02-06T18:31:11.752221" level="INFO">Opening browser 'Chrome' to base url 'http://192.168.137.8:3355/home'.</msg>
<arg>http://192.168.137.8:3355/home</arg>
<arg>Chrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2024-02-06T18:31:11.752221" elapsed="3.279421"/>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" start="2024-02-06T18:31:15.032638" elapsed="0.209441"/>
</kw>
<status status="PASS" start="2024-02-06T18:31:11.749039" elapsed="3.493415"/>
</kw>
<kw name="Invalid login">
<msg time="2024-02-06T18:31:15.246068" level="FAIL">Variable '${email}' not found.</msg>
<arg>${email}</arg>
<arg>${password}</arg>
<status status="FAIL" start="2024-02-06T18:31:15.243076" elapsed="0.002992">Variable '${email}' not found.</status>
</kw>
<kw name="Finish Testcases" type="TEARDOWN">
<kw name="Close Browser" owner="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" start="2024-02-06T18:31:15.249060" elapsed="2.429712"/>
</kw>
<status status="PASS" start="2024-02-06T18:31:15.247066" elapsed="2.432689"/>
</kw>
<status status="FAIL" start="2024-02-06T18:31:11.746021" elapsed="5.934724">Variable '${email}' not found.</status>
</test>
<doc>Verify login functionality</doc>
<status status="FAIL" start="2024-02-06T18:31:11.423136" elapsed="6.263593"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="SalesTracker login csv">SalesTracker login csv</stat>
</suite>
</statistics>
<errors>
<msg time="2024-02-06T18:31:11.735522" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\imranuddinms\PycharmProjects\SaleTracker_Automation\Tests\NormalWay\SalesTracker_login_csv.robot", line 0</msg>
<msg time="2024-02-06T18:31:11.737517" level="ERROR">In source file:
  File "TestData/Testdata.csv", line 0</msg>
<msg time="2024-02-06T18:31:11.744495" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\imranuddinms\PycharmProjects\SaleTracker_Automation\Tests\NormalWay\TestData\Testdata.csv but file does not exist.</msg>
</errors>
</robot>
